/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiopush_jni_PushNative */

#ifndef _Included_com_example_audiopush_jni_PushNative
#define _Included_com_example_audiopush_jni_PushNative
#include <android/log.h>

#define LOG_TAG "Test_Jni"
//用于打印debug级别的log信息
//__VA_ARGS__ 可变参数
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

//用于打印info级别的log信息
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

//用于打印error级别的log信息
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_release
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    fireVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_fireVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_audiopush_jni_PushNative
 * Method:    fireAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_example_audiopush_jni_PushNative_fireAudio
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
